#!/bin/sh

BASE_DIR="/opt/antidpi"
CONFIG_DIR="/etc/antidpi"
PID_FILE="/var/run/antidpi.pid"

start_antidpi() {

    echo "Starting Anti-DPI..."

    if [ -f "$PID_FILE" ]; then
        echo "Already running"
        exit 1
    fi

    STRATEGY="fake,split2"

    if [ -f "$CONFIG_DIR/best-strategy.conf" ]; then
        STRATEGY=$(cat $CONFIG_DIR/best-strategy.conf)
        echo "Using detected strategy: $STRATEGY"
    fi

    nfqws \
        --dpi-desync=$STRATEGY \
        --dpi-desync-split-pos=1 \
        --dpi-desync-repeats=3 \
        --dpi-desync-fooling=badsum \
        --filter-tcp=80,443 &

    echo $! > $PID_FILE

    echo "Anti-DPI started"
}


stop_antidpi() {

    echo "Stopping Anti-DPI..."

    if [ ! -f "$PID_FILE" ]; then
        echo "Not running"
        exit 1
    fi

    kill $(cat $PID_FILE)

    rm -f $PID_FILE

    echo "Stopped"
}


status_antidpi() {

    if [ -f "$PID_FILE" ]; then
        echo "Anti-DPI running (PID $(cat $PID_FILE))"
    else
        echo "Anti-DPI stopped"
    fi

}


restart_antidpi() {

    stop_antidpi
    start_antidpi

}


case "$1" in

 start)
  start_antidpi
 ;;

 stop)
  stop_antidpi
 ;;

 restart)
  restart_antidpi
 ;;

 status)
  status_antidpi
 ;;

 test)
  sh /usr/lib/antidpi/dpi-detector.sh
 ;;

 update)
  sh /usr/lib/antidpi/update-hostlists.sh
 ;;

 auto)
  sh /usr/lib/antidpi/strategy-detector.sh
 ;;

 *)
  echo "Usage: antidpi {start|stop|restart|status|test|update|auto}"
 ;;

esac